#!/bin/ksh

# Required Postgres connection info
PGUSER="<user>"
PGDATABASE="<database>"
PGHOST="<hostname>"
PGPORT="5432"  # or whatever your port is
OUTPUT_FILE="postgres_table_stats.csv"

# Optional password handling (or use .pgpass)
# export PGPASSWORD="your_password"

# Run the COPY command directly with psql -c
psql -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" <<EOF
\\COPY (SELECT 'XHB_CONFIG_PROP' AS table_name, COUNT(*) AS record_count, 'NO DATE' AS last_update FROM PDDA.XHB_CONFIG_PROP UNION ALL SELECT 'XHB_CONFIGURED_PUBLIC_NOTICE', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM PDDA.XHB_CONFIGURED_PUBLIC_NOTICE UNION ALL SELECT 'XHB_COURT', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM PDDA.XHB_COURT UNION ALL SELECT 'XHB_COURT_ROOM', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM PDDA.XHB_COURT_ROOM UNION ALL SELECT 'XHB_COURT_SATELLITE', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM PDDA.XHB_COURT_SATELLITE UNION ALL SELECT 'XHB_COURT_SITE', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM PDDA.XHB_COURT_SITE UNION ALL SELECT 'XHB_COURT_LOG_EVENT_DESC', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM PDDA.XHB_COURT_LOG_EVENT_DESC UNION ALL SELECT 'XHB_REF_HEARING_TYPE', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM PDDA.XHB_REF_HEARING_TYPE UNION ALL SELECT 'XHB_REF_JUDGE', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM PDDA.XHB_REF_JUDGE UNION ALL SELECT 'XHB_REF_JUSTICE', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM PDDA.XHB_REF_JUSTICE UNION ALL SELECT 'XHB_REF_PDDA_MESSAGE_TYPE', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM PDDA.XHB_REF_PDDA_MESSAGE_TYPE UNION ALL SELECT 'XHB_REF_SYSTEM_CODE', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM PDDA.XHB_REF_SYSTEM_CODE) TO '$OUTPUT_FILE' WITH CSV;
EOF
