Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (243, 'XHB_DEFENDANT_ON_CASE_HISTORY', 'AUD_DEFENDANT_ON_CASE_HISTORY', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (250, 'XHB_COURTEL_LIST', 'AUD_COURTEL_LIST', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (255, 'XHB_CPP_LIST', 'AUD_CPP_LIST', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (259, 'XHB_REMAND_REASON_DESCRIPTION', 'AUD_REMAND_REASON_DESCRIPTION', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (260, 'XHB_REMAND_REASONS', 'AUD_REMAND_REASONS', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (208, 'XHB_REF_MONITORING_CATEGORY', 'AUD_REF_MONIROTING_CATEGORY', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (209, 'XHB_CHARGES_LOG', 'AUD_CHARGES_LOG', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (210, 'XHB_CASE_NUMBER_SEQ_GENERATOR', 'AUD_CASE_NUMBER_SEQ_GENERATOR', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (211, 'XHB_REF_EMAIL_RECIPIENTS', 'AUD_REF_EMAIL_RECIPIENTS', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (212, 'XHB_LEGAL_AID_AMENDMENT', 'AUD_LEGAL_AID_AMENDMENT', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (213, 'XHB_CASE_LISTING_ENTRY', 'AUD_CASE_LISTING_ENTRY', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (214, 'XHB_REF_LISTING_DATA', 'AUD_REF_LISTING_DATA', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (215, 'XHB_DIARY_NOTE_ENTRY', 'AUD_DIARY_NOTE_ENTRY', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (216, 'XHB_TIME_RQMT_DEFT_ATTENDING', 'AUD_TIME_RQMT_DEFT_ATTENDING', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (228, 'XHB_PUB_RUNNING_LIST', 'AUD_PUB_RUNNING_LIST', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (218, 'XHB_REF_JUDGE_TICKET', 'AUD_REF_JUDGE_TICKET', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (258, 'XHB_REF_APP_RES_D20_MAP', 'AUD_REF_APP_RES_D20_MAP', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (220, 'XHB_CASE_DIARY_FIXTURE', 'AUD_CASE_DIARY_FIXTURE', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (221, 'XHB_CASE_NON_AVAIL_DAYS', 'AUD_CASE_NON_AVAIL_DAYS', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (222, 'XHB_LIST', 'AUD_LIST', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (223, 'XHB_CASE_ON_LIST', 'AUD_CASE_ON_LIST', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (224, 'XHB_SITTING_ON_LIST', 'AUD_SITTING_ON_LIST', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (225, 'XHB_FIXTURE_DEFT_ATTENDING', 'AUD_FIXTURE_DEFT_ATTENDING', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (226, 'XHB_BW_HISTORY', 'AUD_BW_HISTORY', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (232, 'XHB_MIS_EVENT_LOG', 'AUD_MIS_EVENT_LOG', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (229, 'XHB_MONETARY_ORDER_TRACKING', 'AUD_MONETARY_ORDER_TRACKING', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (237, 'XHB_CASE_HISTORY', 'AUD_CASE_HISTORY', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (231, 'XHB_REF_EVENT_DESCRIPTION', 'AUD_REF_EVENT_DESCRIPTION', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (233, 'XHB_DEF_ON_CASE_ON_LIST', 'AUD_DEF_ON_CASE_ON_LIST', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (242, 'XHB_JUDGE_USAGE', 'AUD_JUDGE_USAGE', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (256, 'XHB_REFUSED_BROADCAST_CASE', 'AUD_REFUSED_BROADCAST_CASE', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (236, 'XHB_REF_CALENDAR', 'AUD_REF_CALENDAR', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (238, 'XHB_REF_CRACKED_EFFECTIVE', 'AUD_REF_CRACKED_EFFECTIVE', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (239, 'XHB_REPORT_LOG', 'AUD_REPORT_LOG', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (240, 'XHB_DEF_ON_CASE_REF_SOL_FIRM', 'AUD_DEF_ON_CASE_REF_SOL_FIRM', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (241, 'XHB_COURT_ROOM_USAGE', 'AUD_COURT_ROOM_USAGE', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (257, 'XHB_D20_OFFENCE_LINK', 'AUD_D20_OFFENCE_LINK', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (263, 'XHB_REF_DAR_RETENTION_POLICIES', 'AUD_REF_DAR_RETENTION_POLICIES', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (264, 'XHB_REF_DISP_RETENTION_POLICY', 'AUD_REF_DISP_RETENTION_POLICY', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (265, 'XHB_DAR_RETENTION_POLICY', 'AUD_DAR_RETENTION_POLICY', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (252, 'XHB_CPP_FORMATTING', 'AUD_CPP_FORMATTING', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (253, 'XHB_CPP_FORMATTING_MERGE', 'AUD_CPP_FORMATTING_MERGE', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (254, 'XHB_CPP_STAGING_INBOUND', 'AUD_CPP_STAGING_INBOUND', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (244, 'XHB_DEFENDANT_ON_CASE', 'AUD_DEFENDANT_ON_CASE', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (245, 'XHB_CASE', 'AUD_CASE', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (246, 'XHB_DEFENDANT', 'AUD_DEFENDANT', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (247, 'XHB_PLEA', 'AUD_PLEA', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (248, 'XHB_SITTING', 'AUD_SITTING', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (249, 'XHB_SCHEDULED_HEARING', 'AUD_SCHEDULED_HEARING', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (261, 'XHB_REF_AGGRAVATING_REASONS', 'AUD_REF_AGGRAVATING_REASONS', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (262, 'XHB_AGGRAVATING_REASONS', 'AUD_AGGRAVATING_REASONS', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (266, 'XHB_REF_STATUS_CODES', 'AUD_REF_STATUS_CODES', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (267, 'XHB_REF_PDDA_MESSAGE_TYPE', 'AUD_REF_PDDA_MESSAGE_TYPE', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (268, 'XHB_PDDA_BATCH', 'AUD_PDDA_BATCH', 'Y');
Insert into XHB_SYS_AUDIT
   (SYS_AUDIT_ID, TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE)
 Values
   (269, 'XHB_PDDA_MESSAGE', 'AUD_PDDA_MESSAGE', 'Y');
COMMIT;
