Insert into XHB_DEFINITIVE_PUBLIC_NOTICE
   (DEFINITIVE_PN_ID, DEFINITIVE_PN_DESC, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, 
    LAST_UPDATED_BY, VERSION, PRIORITY)
 Values
   (100, 'Reporting restrictions. For details please see Court Manager.', TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 
    'XHIBIT', 1, 10);
Insert into XHB_DEFINITIVE_PUBLIC_NOTICE
   (DEFINITIVE_PN_ID, DEFINITIVE_PN_DESC, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, 
    LAST_UPDATED_BY, VERSION, PRIORITY)
 Values
   (200, 'In chambers, no entry.', TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 
    'XHIBIT', 1, 20);
Insert into XHB_DEFINITIVE_PUBLIC_NOTICE
   (DEFINITIVE_PN_ID, DEFINITIVE_PN_DESC, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, 
    LAST_UPDATED_BY, VERSION, PRIORITY)
 Values
   (300, 'Members of the public are requested not to enter.', TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 
    'XHIBIT', 1, 30);
Insert into XHB_DEFINITIVE_PUBLIC_NOTICE
   (DEFINITIVE_PN_ID, DEFINITIVE_PN_DESC, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, 
    LAST_UPDATED_BY, VERSION, PRIORITY)
 Values
   (400, 'TV link in progress - please enter quietly.', TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 
    'XHIBIT', 1, 40);
Insert into XHB_DEFINITIVE_PUBLIC_NOTICE
   (DEFINITIVE_PN_ID, DEFINITIVE_PN_DESC, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, 
    LAST_UPDATED_BY, VERSION, PRIORITY)
 Values
   (500, 'Video being played - please enter quietly.', TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 
    'XHIBIT', 1, 50);
Insert into XHB_DEFINITIVE_PUBLIC_NOTICE
   (DEFINITIVE_PN_ID, DEFINITIVE_PN_DESC, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, 
    LAST_UPDATED_BY, VERSION, PRIORITY)
 Values
   (600, 'If you wish to enter, please do so quietly.', TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 
    'XHIBIT', 1, 60);
Insert into XHB_DEFINITIVE_PUBLIC_NOTICE
   (DEFINITIVE_PN_ID, DEFINITIVE_PN_DESC, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, 
    LAST_UPDATED_BY, VERSION, PRIORITY)
 Values
   (700, 'Reporting restrictions lifted.', TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 
    'XHIBIT', 1, 70);
Insert into XHB_DEFINITIVE_PUBLIC_NOTICE
   (DEFINITIVE_PN_ID, DEFINITIVE_PN_DESC, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, 
    LAST_UPDATED_BY, VERSION, PRIORITY)
 Values
   (800, 'Please switch off mobile phones.', TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 
    'XHIBIT', 1, 80);
Insert into XHB_DEFINITIVE_PUBLIC_NOTICE
   (DEFINITIVE_PN_ID, DEFINITIVE_PN_DESC, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, 
    LAST_UPDATED_BY, VERSION, PRIORITY)
 Values
   (900, 'Food and drink must not be consumed in the courtrooms.', TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 
    'XHIBIT', 1, 90);
Insert into XHB_DEFINITIVE_PUBLIC_NOTICE
   (DEFINITIVE_PN_ID, DEFINITIVE_PN_DESC, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, 
    LAST_UPDATED_BY, VERSION, PRIORITY)
 Values
   (1000, 'Bench warrant in progress.', TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/25/2003 4:51:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 
    'XHIBIT', 1, 100);
COMMIT;
