Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (151, 'LINCOLN', 'A', 24, 120905, 
    TO_DATE('4/1/2005 7:17:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('4/1/2005 7:17:50 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '432');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (428, 'HARROW', 'A', 52, 290310, 
    TO_DATE('9/7/2005 7:33:01 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2005 7:33:01 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '468');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (484, 'BIRMINGHAM', 'A', 58, 330721, 
    TO_DATE('10/12/2005 7:29:11 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/12/2005 7:29:11 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '404', 'Q');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (485, '4 NEWTON STREET', 'D', 58, 330722, 
    TO_DATE('10/12/2005 7:29:13 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/12/2005 7:29:13 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site D', '404', 'N');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (11, 'LUTON', 'A', 8, 49083, 
    TO_DATE('12/3/2004 7:25:32 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/3/2004 7:25:32 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '476');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (12, 'ST ALBANS', 'A', 9, 49084, 
    TO_DATE('12/3/2004 7:29:17 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/3/2004 7:29:17 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '450');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (420, 'MIDDLESEX GUILDHALL', 'A', 49, 274046, 
    TO_DATE('9/2/2005 7:15:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/2/2005 7:15:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '464');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (439, 'INNER LONDON', 'A', 54, 303367, 
    TO_DATE('9/14/2005 7:16:59 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/14/2005 7:16:59 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '440');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (429, 'BLACKFRIARS', 'A', 53, 290311, 
    TO_DATE('9/7/2005 7:35:45 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2005 7:35:45 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '428');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (595, 'GREAT GRIMSBY', 'A', 67, 383483, 
    TO_DATE('11/25/2005 7:28:58 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('11/25/2005 7:28:58 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '425');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (903, 'MANCHESTER', 'A', 79, 478777, 
    TO_DATE('2/24/2006 7:32:04 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/24/2006 7:32:04 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '435');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (1113, 'WARRINGTON', 'L', 69, 495096, 
    TO_DATE('7/3/2006 1:47:06 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('7/3/2006 1:47:06 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site L', '775', 'WAR');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (162, 'NOTTINGHAM', 'A', 25, 129260, 
    TO_DATE('4/8/2005 7:20:18 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('4/8/2005 7:20:18 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '444');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (394, 'CROYDON', 'A', 47, 259785, 
    TO_DATE('8/18/2005 10:11:51 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('8/18/2005 10:11:51 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '418');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (421, 'WOOD GREEN', 'A', 50, 274047, 
    TO_DATE('9/2/2005 7:15:41 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/2/2005 7:15:41 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '469');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (782, 'AYLESBURY', 'A', 78, 459031, 
    TO_DATE('2/10/2006 7:31:38 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/10/2006 7:31:38 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '401');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (361, 'SOUTHWARK', 'A', 44, 235688, 
    TO_DATE('8/3/2005 7:05:44 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('8/3/2005 7:05:44 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '471');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (318, 'PLYMOUTH', 'A', 39, 209189, 
    TO_DATE('7/15/2005 7:24:35 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('7/15/2005 7:24:35 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '446');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (425, 'KINGSTON UPON THAMES', 'A', 51, 284796, 
    TO_DATE('9/5/2005 8:28:48 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/5/2005 8:28:48 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '427');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (502, 'WOLVERHAMPTON', 'A', 59, 340034, 
    TO_DATE('10/28/2005 7:22:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/21/2005 7:38:44 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 
    'Court Site A', '421', 'WV');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (503, 'WEST MIDLANDS COURT CENTRE', 'B', 59, 340035, 
    TO_DATE('10/21/2005 7:38:46 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/21/2005 7:38:46 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site B', '421', 'WF');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (504, 'COVENTRY', 'A', 60, 340036, 
    TO_DATE('10/21/2005 7:41:27 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/21/2005 7:41:27 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '417');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (5, 'DURHAM', 'A', 5, 41904, 
    TO_DATE('11/24/2004 7:30:56 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('11/24/2004 7:30:56 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '422');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (75, 'BRISTOL', 'A', 12, 68598, 
    TO_DATE('1/28/2005 7:14:40 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('1/28/2005 7:14:40 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '408');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (41, 'BASILDON', 'A', 10, 58282, 
    TO_DATE('12/22/2004 8:29:47 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/22/2004 8:29:47 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '461', 'Bas');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (42, 'SOUTHEND', 'B', 10, 58283, 
    TO_DATE('12/22/2004 8:29:49 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/22/2004 8:29:49 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site B', '772', 'SOS');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (380, 'WOOLWICH', 'A', 46, 244766, 
    TO_DATE('8/12/2005 7:29:27 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('8/12/2005 7:29:27 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '472');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (379, 'CROYDON_MOVED', 'A', 45, 244765, 
    TO_DATE('8/18/2005 10:11:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('8/12/2005 7:27:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 
    'Court Site A', '000');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (150, 'DONCASTER', 'A', 23, 120904, 
    TO_DATE('4/1/2005 7:16:59 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('4/1/2005 7:16:59 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '420');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (81, 'GLOUCESTER', 'A', 14, 73999, 
    TO_DATE('2/4/2005 7:19:10 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/4/2005 7:19:10 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '424');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (358, 'ISLEWORTH_MOVED', 'A', 43, 225134, 
    TO_DATE('2/4/2008 2:12:02 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('7/29/2005 7:35:02 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 
    'Court Site A', '000');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (96, 'BURNLEY', 'A', 16, 87213, 
    TO_DATE('2/18/2005 6:05:14 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/18/2005 6:05:14 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '409');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (477, 'MERTHYR TYDFIL', 'A', 57, 326118, 
    TO_DATE('10/7/2005 7:24:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/7/2005 7:24:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '437');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (88, 'BARROW-IN-FURNESS', 'C', 15, 81399, 
    TO_DATE('2/11/2005 7:32:19 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/11/2005 7:32:19 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site C', '751', 'B');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (54, 'CHELMSFORD', 'A', 11, 62938, 
    TO_DATE('1/10/2005 7:27:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('1/10/2005 7:27:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '414');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (87, 'PRESTON', 'A', 15, 81398, 
    TO_DATE('2/11/2005 7:32:17 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/11/2005 7:32:17 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '448', 'R');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (89, 'LANCASTER', 'D', 15, 81400, 
    TO_DATE('2/11/2005 7:32:19 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/11/2005 7:32:19 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site D', '768', 'L');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (90, 'PRESTON [THE SESSIONS HOUSE]', 'B', 15, 81401, 
    TO_DATE('2/11/2005 7:32:19 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/11/2005 7:32:19 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site B', '448', 'S');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (519, 'CARLISLE', 'A', 62, 350832, 
    TO_DATE('10/28/2005 7:29:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/28/2005 7:29:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '412');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (132, 'LEICESTER', 'A', 21, 108964, 
    TO_DATE('3/11/2005 7:05:58 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('3/11/2005 7:05:58 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '430');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (328, 'CENTRAL CRIMINAL COURT', 'A', 41, 217244, 
    TO_DATE('7/20/2005 7:16:34 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('7/20/2005 7:16:34 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '413');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (615, 'DORCHESTER', 'A', 68, 395511, 
    TO_DATE('4/26/2012 2:03:30 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/2/2005 7:35:12 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 3, 
    'Court Site A', '407');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (460, 'NEWPORT CROWN COURT', 'C', 55, 315276, 
    TO_DATE('9/30/2005 7:33:45 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/30/2005 7:33:45 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site C', '441', 'N');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (716, 'NEWPORT, ISLE OF WIGHT', 'A', 72, 436333, 
    TO_DATE('1/27/2006 7:49:45 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('1/27/2006 7:49:45 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '478');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (459, 'CARDIFF', 'A', 55, 315275, 
    TO_DATE('9/30/2005 7:33:43 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/30/2005 7:33:43 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '411', 'C');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (117, 'CANTERBURY', 'A', 19, 99616, 
    TO_DATE('3/7/2005 5:05:52 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('3/7/2005 5:05:52 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '479');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (118, 'MAIDSTONE', 'A', 20, 99617, 
    TO_DATE('3/7/2005 5:07:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('3/7/2005 5:07:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '434');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (309, 'EXETER', 'A', 38, 203376, 
    TO_DATE('7/8/2005 7:32:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('7/8/2005 7:32:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '423', 'E');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (310, 'BARNSTAPLE', 'E', 38, 203377, 
    TO_DATE('7/8/2005 7:32:11 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('7/8/2005 7:32:11 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site E', '750', 'B');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (80, 'TAUNTON', 'A', 13, 73998, 
    TO_DATE('2/4/2005 7:16:24 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/4/2005 7:16:24 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '459');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (702, 'NORTHAMPTON', 'A', 71, 428892, 
    TO_DATE('1/20/2006 7:41:25 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('1/20/2006 7:41:25 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '442');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (731, 'WINCHESTER', 'A', 75, 449905, 
    TO_DATE('2/2/2006 7:33:04 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/2/2006 7:33:04 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '465');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (642, 'CHESTER', 'A', 69, 405554, 
    TO_DATE('12/16/2005 7:29:06 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/16/2005 7:29:06 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '415', 'CHE');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (643, 'MOLD', 'B', 69, 405555, 
    TO_DATE('12/16/2005 7:29:08 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/16/2005 7:29:08 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site B', '769', 'MOL');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (644, 'CAERNARFON', 'C', 69, 405556, 
    TO_DATE('12/16/2005 7:29:08 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/16/2005 7:29:08 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site C', '755', 'CAE');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (645, 'DOLGELLAU', 'D', 69, 405557, 
    TO_DATE('12/16/2005 7:29:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/16/2005 7:29:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site D', '758', 'DOL');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (646, 'WELSHPOOL', 'E', 69, 405558, 
    TO_DATE('12/16/2005 7:29:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/16/2005 7:29:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site E', '774', 'WEL');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (647, 'KNUTSFORD', 'F', 69, 405559, 
    TO_DATE('12/16/2005 7:29:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/16/2005 7:29:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site F', '767', 'KNU');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (6, 'TEESSIDE', 'A', 6, 45157, 
    TO_DATE('11/29/2004 7:32:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('11/29/2004 7:32:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '460');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (196, 'KINGS LYNN', 'B', 27, 143340, 
    TO_DATE('5/6/2005 7:29:02 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('5/6/2005 7:29:02 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site B', '765', 'K');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (169, 'DERBY', 'A', 26, 135175, 
    TO_DATE('4/15/2005 7:30:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('4/15/2005 7:30:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '419');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (195, 'NORWICH', 'A', 27, 143339, 
    TO_DATE('5/6/2005 7:29:01 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('5/6/2005 7:29:01 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '443', 'N');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (717, 'PORTSMOUTH', 'A', 73, 436334, 
    TO_DATE('1/27/2006 7:51:13 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('1/27/2006 7:51:13 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '447');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (1, 'SNARESBROOK_MOVED', 'A', 1, 1, 
    TO_DATE('2/6/2008 4:40:55 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/25/2003 4:51:37 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 5, 
    'Court Site A', '000');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (2, 'DOCKFORD', 'A', 2, 2, 
    TO_DATE('7/24/2004 12:52:53 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/25/2003 4:51:37 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 
    'Court Site A', '499');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (3, 'ISLEWORTH_MOVED', 'I', 3, 3, 
    TO_DATE('7/29/2005 7:34:47 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/25/2003 4:51:37 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 3, 
    'Court Site I', '000');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (146, 'THE LAW COURTS WEST BAR SHEFFIELD', 'A', 22, 115423, 
    TO_DATE('3/24/2005 7:15:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('3/24/2005 7:15:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '451');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (218, 'YORK', 'A', 29, 154401, 
    TO_DATE('5/25/2005 7:27:29 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('5/25/2005 7:27:29 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '467');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (219, 'BRADFORD', 'A', 30, 154402, 
    TO_DATE('5/25/2005 7:28:42 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('5/25/2005 7:28:42 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '402');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (197, ' IPSWICH', 'A', 28, 143341, 
    TO_DATE('5/6/2005 7:49:57 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('5/6/2005 7:30:15 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 
    'Court Site A', '426', 'I');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (198, 'BURY ST EDMUNDS', 'B', 28, 143342, 
    TO_DATE('5/6/2005 7:30:15 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('5/6/2005 7:30:15 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site B', '754', 'B');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (571, 'BOURNEMOUTH CROWN AND COUNTY COURTS', 'A', 63, 368269, 
    TO_DATE('11/18/2005 7:25:27 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('11/18/2005 7:25:27 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '406');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (572, 'LEWES COMBINED COURT', 'A', 64, 368270, 
    TO_DATE('11/18/2005 7:27:25 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('11/18/2005 7:27:25 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '431', 'L');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (573, 'HOVE TRIAL CENTRE', 'B', 64, 368271, 
    TO_DATE('11/18/2005 7:27:25 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('11/18/2005 7:27:25 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site B', '431', 'H');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (275, 'LIVERPOOL', 'A', 37, 193107, 
    TO_DATE('6/23/2005 7:21:55 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('6/23/2005 7:21:55 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '433');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (227, 'LEEDS', 'A', 31, 163191, 
    TO_DATE('6/1/2005 7:27:16 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('6/1/2005 7:27:16 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '429');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (357, 'GUILDFORD', 'A', 42, 225133, 
    TO_DATE('7/29/2005 7:31:59 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('7/29/2005 7:31:59 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '474');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (251, 'SHREWSBURY', 'A', 34, 170713, 
    TO_DATE('6/10/2005 7:35:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('6/10/2005 7:35:22 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '452');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (260, ' WARWICK', 'A', 35, 183581, 
    TO_DATE('6/17/2005 7:22:02 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('6/17/2005 7:22:02 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '463');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (403, 'KINGSTON UPON THAMES_MOVED', 'A', 48, 266176, 
    TO_DATE('9/5/2005 8:28:36 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('8/24/2005 7:03:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 
    'Court Site A', '000');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (780, 'READING', 'A', 76, 459029, 
    TO_DATE('2/10/2006 7:28:25 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/10/2006 7:28:25 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '449');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (724, 'SOUTHAMPTON', 'A', 74, 444953, 
    TO_DATE('1/31/2006 7:22:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('1/31/2006 7:22:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '454');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (461, 'SWANSEA_MOVED', 'A', 56, 315277, 
    TO_DATE('2/4/2008 2:27:45 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/30/2005 7:38:33 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 
    'Court Site A', '000', 'S');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (462, 'CARMARTHEN_MOVED', 'B', 56, 315278, 
    TO_DATE('2/4/2008 2:27:45 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/30/2005 7:38:34 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 
    'Court Site B', '000', 'C');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (463, 'HAVERFORDWEST_MOVED', 'C', 56, 315279, 
    TO_DATE('2/4/2008 2:27:45 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/30/2005 7:38:34 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 
    'Court Site C', '000', 'H');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (464, 'THE CRIMINAL COURT, GUILDHALL_MOVED', 'D', 56, 315280, 
    TO_DATE('2/4/2008 2:27:45 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/30/2005 7:38:34 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 
    'Court Site D', '000', 'G');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (781, 'OXFORD', 'A', 77, 459030, 
    TO_DATE('2/10/2006 7:30:11 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/10/2006 7:30:11 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '445');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (584, 'CHICHESTER', 'A', 65, 377587, 
    TO_DATE('11/22/2005 7:35:43 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('11/22/2005 7:35:43 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '416');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (517, 'NEWCASTLE UPON TYNE', 'A', 61, 350830, 
    TO_DATE('10/28/2005 7:26:07 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/28/2005 7:26:07 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '439', 'NC');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (518, 'MOOT HALL', 'B', 61, 350831, 
    TO_DATE('10/28/2005 7:26:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('10/28/2005 7:26:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site B', '439', 'NMH');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (103, 'CAMBRIDGE', 'A', 17, 91541, 
    TO_DATE('2/25/2005 7:15:48 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/25/2005 7:15:48 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '410');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (249, 'STOKE ON TRENT', 'A', 32, 170711, 
    TO_DATE('6/10/2005 7:31:10 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('6/10/2005 7:31:10 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '456');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (250, 'STAFFORD', 'A', 33, 170712, 
    TO_DATE('6/10/2005 7:34:11 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('6/10/2005 7:34:11 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '455');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (319, 'TRURO', 'A', 40, 209190, 
    TO_DATE('7/15/2005 7:25:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('7/15/2005 7:25:09 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '477');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (104, 'PETERBOROUGH', 'A', 18, 91542, 
    TO_DATE('2/25/2005 7:17:31 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/25/2005 7:17:31 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '473');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (686, 'WARRINGTON', 'A', 70, 421710, 
    TO_DATE('1/13/2006 7:35:18 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('1/13/2006 7:35:18 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '462');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (261, 'WORCESTER SHIRE HALL', 'A', 36, 183582, 
    TO_DATE('6/17/2005 7:25:47 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('6/17/2005 7:25:47 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '466', 'W');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (262, 'HEREFORD', 'B', 36, 183583, 
    TO_DATE('6/17/2005 7:25:48 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('6/17/2005 7:25:48 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site B', '762', 'H');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (594, 'KINGSTON UPON HULL', 'A', 66, 383482, 
    TO_DATE('11/25/2005 7:28:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('11/25/2005 7:28:05 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '403');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID)
 Values
   (1612, 'SNARESBROOK', 'A', 83, 514102, 
    TO_DATE('2/6/2008 4:41:20 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/6/2008 4:41:20 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site A', '453');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME)
 Values
   (1620, 'PETERBOROUGH MAGISTRATES', 'Z', 18, 560722, 
    TO_DATE('3/21/2013 3:32:13 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('3/21/2013 3:32:13 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 1, 
    'Court Site Z', '473', 'Z');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    OBS_IND, DISPLAY_NAME, CREST_COURT_ID)
 Values
   (1607, 'ISLEWORTH', 'A', 81, 514097, 
    TO_DATE('10/18/2023 12:21:56 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/4/2008 2:13:03 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 
    'N', 'Court Site A', '475');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    OBS_IND, DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME, SITE_GROUP, 
    FLOATER_TEXT, LIST_NAME)
 Values
   (1608, 'SWANSEA', 'A', 82, 514098, 
    TO_DATE('5/3/2023 12:24:07 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/4/2008 2:28:05 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'Administrator1', 30, 
    'N', 'Court Site A', '457', 'S', 1, 
    'The following cases may be heard at Swansea or Norwich, or any other damn place we tell you', 'SWANSEA');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME, SITE_GROUP, LIST_NAME)
 Values
   (1609, 'CARMARTHEN', 'B', 82, 514099, 
    TO_DATE('5/2/2024 12:07:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/4/2008 2:28:05 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'List Officer2', 3, 
    'Court Site B', '756', 'C', 2, 'CARMARTHEN');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME, SITE_GROUP, LIST_NAME)
 Values
   (1610, 'HAVERFORDWEST', 'C', 82, 514100, 
    TO_DATE('6/13/2019 11:32:55 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/4/2008 2:28:05 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'Administrator1', 3, 
    'Court Site C', '761', 'H', 3, 'HAVERFORDWEST');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    OBS_IND, DISPLAY_NAME, CREST_COURT_ID, SHORT_NAME, SITE_GROUP, 
    LIST_NAME)
 Values
   (1611, 'THE CRIMINAL COURT, GUILDHALL', 'D', 82, 514101, 
    TO_DATE('8/29/2019 12:44:25 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/4/2008 2:28:06 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'Administrator2', 4, 
    'N', 'Court Site D', '457', 'G', 4, 
    'GUILDHALL');
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    OBS_IND, DISPLAY_NAME, SHORT_NAME, SITE_GROUP)
 Values
   (1635, '   SPACE TESTER      ', 'C', 22, 567671, 
    TO_DATE('7/10/2019 11:15:38 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('7/10/2019 11:15:38 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'Administrator1', 'Administrator1', 1, 
    'N', '   SPACE TESTER      ', 'SHEFFC', 3);
Insert into XHB_COURT_SITE
   (COURT_SITE_ID, COURT_SITE_NAME, COURT_SITE_CODE, COURT_ID, ADDRESS_ID, 
    LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, 
    OBS_IND, DISPLAY_NAME, SHORT_NAME, SITE_GROUP, LIST_NAME)
 Values
   (1634, 'Sheffield South', 'B', 22, 567670, 
    TO_DATE('7/9/2019 2:08:55 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('7/9/2019 1:41:10 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Administrator1', 'Administrator1', 4, 
    'N', 'Sheffield South', 'SHEFFB', 1, 'SHEFFIELD SOUTH');
COMMIT;
