Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, PARTY_RESPONSIBLE, LAST_UPDATE_DATE, 
    CREATION_DATE, LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (1, 'A', 'Acceptable guilty plea(s) entered late to some or all charge / counts on the charge sheet, offered for first time by the defence', 'D', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 'C');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, PARTY_RESPONSIBLE, LAST_UPDATE_DATE, 
    CREATION_DATE, LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (2, 'B', 'Acceptable guilty plea(s) entered late to some or all charge / counts on the charge sheet, previously rejected by the prosecution', 'P', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 'C');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, PARTY_RESPONSIBLE, LAST_UPDATE_DATE, 
    CREATION_DATE, LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (3, 'C', 'Acceptable guilty plea(s) to alternative new charge (not previously on the charge sheet), first time offered by defence', 'D', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 'C');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, PARTY_RESPONSIBLE, LAST_UPDATE_DATE, 
    CREATION_DATE, LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (4, 'D', 'Acceptable guilty plea(s) to alternative new charge (not previously on the charge sheet), previously rejected by the prosecution', 'P', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 'C');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, PARTY_RESPONSIBLE, LAST_UPDATE_DATE, 
    CREATION_DATE, LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (5, 'E', 'Defendant bound over, acceptable to prosecution, offered for the first time by the defence', 'D', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 'C');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (6, 'E1', 'Effective trial', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'E');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, PARTY_RESPONSIBLE, LAST_UPDATE_DATE, 
    CREATION_DATE, LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (7, 'F', 'Defendant bound over, now acceptable to prosecution – previously rejected by prosecution', 'P', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 'C');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, PARTY_RESPONSIBLE, LAST_UPDATE_DATE, 
    CREATION_DATE, LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (8, 'G', 'Unable to proceed with trial because defendant incapable through alcohol / drugs', 'D', TO_DATE('1/9/2019 6:04:12 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 3, 'C');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, PARTY_RESPONSIBLE, LAST_UPDATE_DATE, 
    CREATION_DATE, LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (9, 'H', 'Defendant deceased', 'D', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 'C');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, PARTY_RESPONSIBLE, LAST_UPDATE_DATE, 
    CREATION_DATE, LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (10, 'I', 'Prosecution end case: insufficient evidence', 'P', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 'C');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, PARTY_RESPONSIBLE, LAST_UPDATE_DATE, 
    CREATION_DATE, LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (11, 'J', 'Prosecution end case: witness absent / withdrawn', 'P', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 'C');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, PARTY_RESPONSIBLE, LAST_UPDATE_DATE, 
    CREATION_DATE, LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (12, 'K', 'Prosecution end case: public interest grounds', 'P', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 'C');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, PARTY_RESPONSIBLE, LAST_UPDATE_DATE, 
    CREATION_DATE, LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (13, 'L', 'Prosecution end case: adjournment refused', 'P', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT', 2, 'C');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (14, 'M1', 'Prosecution not ready: served late notice of additional evidence by defence', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (15, 'M2', 'Prosecution not ready: specify in comments', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (16, 'M3', 'Prosecution failed to disclose unused material', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (17, 'N1', 'Prosecution witness absent: police', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (18, 'N2', 'Prosecution witness absent: professional / expert', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (19, 'N3', 'Prosecution witness absent: other', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (20, 'O1', 'Prosecution advocate engaged in another trial', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (21, 'O2', 'Prosecution advocate failed to attend', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (22, 'P', 'Prosecution increased time estimate – insufficient time for trial to start', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (23, 'Q1', 'Defence not ready: disclosure problems', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (24, 'Q2', 'Defence not ready: specify in comments (inc. no instructions)', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (25, 'Q3', 'Defence asked for additional prosecution witness to attend', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (26, 'R', 'Defence witness absent', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (27, 'S1', 'Defendant absent – did not proceed in absence (judicial discretion)', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (28, 'S2', 'Defendant ill or otherwise unfit to proceed', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (29, 'S3', 'Defendant not produced by PECS', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (30, 'S4', 'Defendant absent – unable to proceed as defendant not notified of place and time of hearing', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (31, 'T', 'Defence increased time estimate – insufficient time for trial to start', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (32, 'U1', 'Defence advocate engaged in other trial', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (33, 'U2', 'Defence advocate failed to attend', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (34, 'V', 'Defendant dismissed advocate', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (35, 'W1', 'Another case over-ran', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (36, 'W2', 'Judge / magistrate availability', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (37, 'W3', 'Case not reached / insufficient cases dropped out / floater not reached', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (38, 'W4', 'Equipment / accommodation failure', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (39, 'W5', 'No interpreter available', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (40, 'X', 'Insufficient jurors available', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (41, 'Y', 'Outstanding committals in a magistrates’ court', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
Insert into XHB_REF_CRACKED_EFFECTIVE
   (REF_CRACKED_EFFECTIVE_ID, CODE, DESCRIPTION, LAST_UPDATE_DATE, CREATION_DATE, 
    LAST_UPDATED_BY, CREATED_BY, VERSION, TRIAL_CODE_TYPE)
 Values
   (42, 'Z', 'Outstanding committals in another Crown Court centre', TO_DATE('9/7/2018 10:24:21 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:10:53 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'I');
COMMIT;
