Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (16, 1113, 'WARRINGTON', TO_DATE('9/7/2018 10:24:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('7/3/2006 1:47:23 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'N');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (1, 460, 'NEWPORT_CROWN_COURT', TO_DATE('9/7/2018 10:24:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/9/2005 11:39:39 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 3, 'N');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (2, 462, 'CARMARTHEN', TO_DATE('9/7/2018 10:24:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/9/2005 11:39:39 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'N');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (3, 196, 'KINGS_LYNN', TO_DATE('9/7/2018 10:24:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/9/2005 11:39:39 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 3, 'N');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (4, 88, 'BARROW-IN-FURNESS', TO_DATE('9/7/2018 10:24:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/9/2005 11:39:39 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'N');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (5, 89, 'LANCASTER', TO_DATE('9/7/2018 10:24:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/9/2005 11:39:39 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'N');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (6, 463, 'HAVERFORDWEST', TO_DATE('9/7/2018 10:24:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/9/2005 11:39:39 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'N');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (7, 42, 'SOUTHEND', TO_DATE('9/7/2018 10:24:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/9/2005 11:39:39 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'N');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (8, 262, 'HEREFORD', TO_DATE('9/7/2018 10:24:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/9/2005 11:39:39 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'N');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (9, 198, 'BURY_ST_EDMUNDS', TO_DATE('9/7/2018 10:24:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/9/2005 11:39:39 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 3, 'N');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (10, 310, 'BARNSTAPLE', TO_DATE('9/7/2018 10:24:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/9/2005 11:39:39 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'N');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (11, 644, 'CAERNARFON', TO_DATE('9/7/2018 10:24:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/16/2005 7:30:04 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'N');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (12, 647, 'KNUTSFORD', TO_DATE('9/7/2018 10:24:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/16/2005 7:30:04 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'N');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (13, 643, 'MOLD', TO_DATE('9/7/2018 10:24:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/16/2005 7:30:04 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'N');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (14, 645, 'DOLGELLAU', TO_DATE('9/7/2018 10:24:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/16/2005 7:30:04 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'N');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (15, 646, 'WELSHPOOL', TO_DATE('9/7/2018 10:24:23 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/16/2005 7:30:04 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2, 'N');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (18, 1631, 'LINCOLN', TO_DATE('1/29/2020 1:08:17 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('12/5/2018 3:08:58 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'Administrator1', 'Court Clerk1', 3, 'Y');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (19, 1609, 'CARMARTHEN', TO_DATE('5/2/2024 12:07:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/6/2020 10:53:02 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'List Officer2', 2, 'Y');
Insert into XHB_COURT_SATELLITE
   (COURT_SATELLITE_ID, COURT_SITE_ID, INTERNET_SATELLITE_NAME, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION, OBS_IND)
 Values
   (20, 1610, 'HAVERFORDWEST', TO_DATE('2/6/2020 10:53:16 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('2/6/2020 10:53:16 AM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 1, 'N');
COMMIT;
