Insert into XHB_COURT_SITE_WELSH
   (COURT_SITE_WELSH_ID, COURT_SITE_NAME, COURT_SITE_ID, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION)
 Values
   (1, 'Llys y Goron yn: Caerdydd', 459, TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 1);
Insert into XHB_COURT_SITE_WELSH
   (COURT_SITE_WELSH_ID, COURT_SITE_NAME, COURT_SITE_ID, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION)
 Values
   (2, 'Llys y Goron yn: Abertawe', 1608, TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 1);
Insert into XHB_COURT_SITE_WELSH
   (COURT_SITE_WELSH_ID, COURT_SITE_NAME, COURT_SITE_ID, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION)
 Values
   (3, 'Llys y Goron yn: Casnewydd', 460, TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 1);
Insert into XHB_COURT_SITE_WELSH
   (COURT_SITE_WELSH_ID, COURT_SITE_NAME, COURT_SITE_ID, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION)
 Values
   (4, 'Llys y Goron yn: Merthyr Tudful', 477, TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 1);
Insert into XHB_COURT_SITE_WELSH
   (COURT_SITE_WELSH_ID, COURT_SITE_NAME, COURT_SITE_ID, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION)
 Values
   (5, 'Llys y Goron yn: Yr Wyddgrug', 643, TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 1);
Insert into XHB_COURT_SITE_WELSH
   (COURT_SITE_WELSH_ID, COURT_SITE_NAME, COURT_SITE_ID, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION)
 Values
   (6, 'Llys y Goron yn: Caernarfon', 644, TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 1);
Insert into XHB_COURT_SITE_WELSH
   (COURT_SITE_WELSH_ID, COURT_SITE_NAME, COURT_SITE_ID, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION)
 Values
   (7, 'Llys y Goron yn: Henffordd', 262, TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 1);
COMMIT;
