Insert into XHB_DISP_MGR_USER_DETAILS
   (USER_ID, USER_NAME, USER_ROLE, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION)
 Values
   (17, 'pp_court_clerk_1', 'ROLE_ADMIN', TO_DATE('7/4/2017 3:44:57 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('7/4/2017 3:44:57 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'pp_court_clerk_4', 'pp_court_clerk_4', 1);
Insert into XHB_DISP_MGR_USER_DETAILS
   (USER_ID, USER_NAME, USER_ROLE, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION)
 Values
   (4, 'pp_court_clerk_4', 'ROLE_ADMIN', TO_DATE('6/7/2017 12:35:57 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2);
Insert into XHB_DISP_MGR_USER_DETAILS
   (USER_ID, USER_NAME, USER_ROLE, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION)
 Values
   (5, 'pp_court_clerk_5', 'ROLE_ADMIN', TO_DATE('6/7/2017 12:35:57 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2);
Insert into XHB_DISP_MGR_USER_DETAILS
   (USER_ID, USER_NAME, USER_ROLE, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION)
 Values
   (7, 'pp_cs_admin_1', 'ROLE_ADMIN', TO_DATE('6/7/2017 12:35:57 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2);
Insert into XHB_DISP_MGR_USER_DETAILS
   (USER_ID, USER_NAME, USER_ROLE, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION)
 Values
   (8, 'mallyav', 'ROLE_ADMIN', TO_DATE('6/7/2017 12:35:57 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('3/6/2017 2:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 2);
Insert into XHB_DISP_MGR_USER_DETAILS
   (USER_ID, USER_NAME, USER_ROLE, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION)
 Values
   (9, 'pp_court_clerk_3', 'ROLE_USER', TO_DATE('6/15/2017 3:20:12 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('6/15/2017 3:20:12 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'XHIBIT', 'XHIBIT', 1);
Insert into XHB_DISP_MGR_USER_DETAILS
   (USER_ID, USER_NAME, USER_ROLE, LAST_UPDATE_DATE, CREATION_DATE, 
    CREATED_BY, LAST_UPDATED_BY, VERSION)
 Values
   (10, 'mmtest', 'ROLE_ADMIN', TO_DATE('6/15/2017 3:42:11 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('6/15/2017 3:42:11 PM', 'MM/DD/YYYY HH:MI:SS AM'), 
    'pp_court_clerk_1', 'pp_court_clerk_1', 1);
COMMIT;
