Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (48, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TRN', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (49, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TRL', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (50, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TNW', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (51, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TIS', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (52, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TWC', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (53, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TPR', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (54, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TPW', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (55, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TFW', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (56, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TFL', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (57, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TRE', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (58, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TBK', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/21/2018 12:12:14 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (22, 'PREDEFINED_LIST_NOTE', 'Order made under s39, CYPA 1933', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (23, 'PREDEFINED_LIST_NOTE', 'Order made under s39, CYPA 1933 (witnesses only)', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (24, 'PREDEFINED_LIST_NOTE', 'Order made under Contempt of Court Act 1981', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (4, 'NOTE_CLASSIFICATION', 'Priority', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/6/2018 7:28:25 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 7:28:25 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (5, 'NOTE_CLASSIFICATION', 'Restricted', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/6/2018 7:28:25 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 7:28:25 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (6, 'NOTE_CLASSIFICATION', 'Standard', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/6/2018 7:28:25 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 7:28:25 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (7, 'PREDEFINED_LIST_NOTE', 'Predefined List Note 1', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/6/2018 7:28:25 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'Y', 2);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (8, 'PREDEFINED_LIST_NOTE', 'Predefined List Note 2', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/6/2018 7:28:25 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'Y', 2);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (25, 'PREDEFINED_LIST_NOTE', 'Orders made under s39, CYPA 1933 & Contempt of Court Act 1981', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (10, 'LIST_TYPE', 'Daily', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/6/2018 8:08:36 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:08:36 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (11, 'LIST_TYPE', 'Warned', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/6/2018 8:08:36 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:08:36 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (12, 'LIST_TYPE', 'Firm', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/6/2018 8:08:36 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:08:36 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (13, 'LIST_TYPE', 'Annotated Warned', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/6/2018 8:08:36 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:08:36 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (14, 'LIST_TYPE', 'Daily Prison', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/6/2018 8:08:36 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:08:36 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (15, 'LIST_TYPE', 'Daily Court Room', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/6/2018 8:08:36 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 8:08:36 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (26, 'PREDEFINED_LIST_NOTE', 'Orders made under s39, CYPA 1933 (witnesses only) & Contempt of Court Act 1981', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (17, 'NOTE_TYPE', 'CN', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/6/2018 10:46:59 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 10:46:59 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (18, 'NOTE_TYPE', 'DCN', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/6/2018 10:46:59 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 10:46:59 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (19, 'NOTE_TYPE', 'GDN', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/6/2018 10:46:59 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 10:46:59 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (20, 'NOTE_TYPE', 'HN', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/6/2018 10:46:59 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 10:46:59 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (21, 'NOTE_TYPE', 'IN', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/6/2018 10:46:59 PM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/6/2018 10:46:59 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (27, 'PREDEFINED_LIST_NOTE', 'Order made under s45, Youth Justice and Criminal Evidence Act 1999', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (28, 'PREDEFINED_LIST_NOTE', 'Order made under s45a, Youth Justice and Criminal Evidence Act 1999', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (29, 'PREDEFINED_LIST_NOTE', 'Order made under s46, Youth Justice and Criminal Evidence Act 1999', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (30, 'PREDEFINED_LIST_NOTE', 'Order made under s49, Children and Young Persons Act 1933', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 9:50:39 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (31, 'LIST_COPY_CASE_SITTING_HEARING_TYPES', 'TRL', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (32, 'LIST_COPY_CASE_SITTING_HEARING_TYPES', 'TPH', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (33, 'LIST_COPY_CASE_SITTING_HEARING_TYPES', 'TRN', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (34, 'LIST_COPY_CASE_SITTING_HEARING_TYPES', 'TNW', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (35, 'LIST_COPY_CASE_SITTING_HEARING_TYPES', 'TBK', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (36, 'LIST_COPY_CASE_SITTING_HEARING_TYPES', 'PHD', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (37, 'LIST_COPY_CASE_SITTING_HEARING_TYPES', 'HRG', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (38, 'LIST_COPY_CASE_SITTING_HEARING_TYPES', 'APH', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (39, 'LIST_STATS_CASE_TRIAL_HEARING_TYPES', 'TRL', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (40, 'LIST_STATS_CASE_TRIAL_HEARING_TYPES', 'TNW', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (41, 'LIST_STATS_CASE_TRIAL_HEARING_TYPES', 'TWC', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (42, 'LIST_STATS_CASE_TRIAL_HEARING_TYPES', 'TPR', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (43, 'LIST_STATS_CASE_TRIAL_HEARING_TYPES', 'TPW', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (44, 'LIST_STATS_CASE_TRIAL_HEARING_TYPES', 'TFW', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (45, 'LIST_STATS_CASE_TRIAL_HEARING_TYPES', 'TFL', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (46, 'LIST_STATS_CASE_TRIAL_HEARING_TYPES', 'TRE', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
Insert into XHB_REF_LISTING_DATA
   (REF_LISTING_DATA_ID, REF_DATA_TYPE, REF_DATA_VALUE, CREATED_BY, LAST_UPDATED_BY, 
    CREATION_DATE, LAST_UPDATE_DATE, OBS_IND, VERSION)
 Values
   (47, 'LIST_STATS_CASE_TRIAL_HEARING_TYPES', 'TBK', 'XHIBIT', 'XHIBIT', 
    TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), TO_DATE('9/7/2018 11:26:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'N', 1);
COMMIT;
