Insert into XHB_DISPLAY_TYPE
   (DISPLAY_TYPE_ID, DESCRIPTION_CODE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, 
    LAST_UPDATE_DATE, VERSION)
 Values
   (1, '18in', 'XHIBIT', TO_DATE('3/20/2004 1:54:12 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 
    TO_DATE('3/20/2004 1:54:12 AM', 'MM/DD/YYYY HH:MI:SS AM'), 1);
Insert into XHB_DISPLAY_TYPE
   (DISPLAY_TYPE_ID, DESCRIPTION_CODE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, 
    LAST_UPDATE_DATE, VERSION)
 Values
   (2, '42in', 'XHIBIT', TO_DATE('3/20/2004 1:54:12 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 
    TO_DATE('3/20/2004 1:54:12 AM', 'MM/DD/YYYY HH:MI:SS AM'), 1);
Insert into XHB_DISPLAY_TYPE
   (DISPLAY_TYPE_ID, DESCRIPTION_CODE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, 
    LAST_UPDATE_DATE, VERSION)
 Values
   (3, 'browser', 'XHIBIT', TO_DATE('3/20/2004 1:54:12 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 
    TO_DATE('3/20/2004 1:54:12 AM', 'MM/DD/YYYY HH:MI:SS AM'), 1);
Insert into XHB_DISPLAY_TYPE
   (DISPLAY_TYPE_ID, DESCRIPTION_CODE, CREATED_BY, CREATION_DATE, LAST_UPDATED_BY, 
    LAST_UPDATE_DATE, VERSION)
 Values
   (6, '19in', 'XHIBIT', TO_DATE('11/24/2004 7:30:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 
    TO_DATE('11/24/2004 7:30:37 AM', 'MM/DD/YYYY HH:MI:SS AM'), 1);
COMMIT;
