server:
  port: 5432

spring:
  application:
    name: pdda-public-display-data-aggregator
  config:
    import: "optional:configtree:/mnt/secrets/pdda/"
  dbMigration:
    # When true, the app will run DB migration on startup.
    # Otherwise, it will just check if all migrations have been applied (and fail to start if not).
    runOnStartup: ${RUN_DB_MIGRATION_ON_STARTUP:true}