# -- Logging configuration --
logging.level.root=INFO
logging.level.uk.gov.hmcts=INFO
logging.level.uk.gov.hmcts.pdda.business.entities=WARN
logging.level.uk.gov.hmcts.pdda.business.services.publicdisplay=WARN
logging.level.uk.gov.hmcts.pdda.common.publicdisplay.types.uri=WARN
logging.level.uk.gov.hmcts.pdda.common.publicdisplay.renderdata=WARN
logging.level.uk.gov.hmcts.pdda.web.publicdisplay.configuration=WARN
logging.level.uk.gov.hmcts.pdda.web.publicdisplay.types.AbstractRenderAndStoreableType=WARN
logging.level.uk.gov.hmcts.pdda.web.publicdisplay.rendering=WARN
logging.level.uk.gov.hmcts.pdda.web.publicdisplay.storage.priv.impl=WARN
logging.level.uk.gov.hmcts.framework.services=INFO
logging.level.com.zaxxer.hikari=INFO
logging.level.org.hibernate=INFO
logging.level.org.hibernate.event.internal.DefaultFlushEntityEventListener=ERROR
logging.level.org.hibernate.hql.internal.ast.QueryTranslatorImpl=ERROR
logging.level.org.springframework=INFO
logging.level.org.springframework.boot.autoconfigure=ERROR
# Enable logging below to debug startup/configuration issues
# logging.level.org.springframework.boot.context.config=DEBUG
# logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
# logging.level.org.springframework.boot.autoconfigure.orm.jpa=DEBUG
# logging.level.org.springframework.orm.jpa=DEBUG

management.endpoints.web.exposure.include=*
management.endpoints.health.show-details=always
management.metrics.enable.hikari=true
#spring.security.enabled=false

spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.out-of-order=true
spring.flyway.validate-on-migrate=false

# Hikari DB Connections
spring.datasource.hikari.leak-detection-threshold=10000
spring.datasource.hikari.maximum-pool-size=80
spring.datasource.hikari.minimum-idle=20
spring.datasource.hikari.idle-timeout=60000

pdda.bais_sftp_hostname=${PDDA_BAIS_SFTP_HOSTNAME}
pdda.bais_cp_sftp_username=${PDDA_BAIS_CP_SFTP_USERNAME}
pdda.bais_cp_sftp_password=${PDDA_BAIS_CP_SFTP_PASSWORD}
pdda.bais_cp_sftp_upload_location=${PDDA_BAIS_CP_SFTP_UPLOAD_LOCATION}
pdda.bais_sftp_username=${PDDA_BAIS_SFTP_USERNAME}
pdda.bais_sftp_password=${PDDA_BAIS_SFTP_PASSWORD}
pdda.bais_sftp_upload_location=${PDDA_BAIS_SFTP_UPLOAD_LOCATION}