java:
  applicationPort: 5432
  image: 'sdshmctspublic.azurecr.io/pdda/public-display-data-aggregator:latest'
  ingressHost: pdda-public-display-data-aggregator.{{ .Values.global.environment }}.platform.hmcts.net
  keyVaults:
    vh-infra-core:
      excludeEnvironmentSuffix: false
      resourceGroup: pdda-{{ .Values.global.environment }}
      usePodIdentity: true
      secrets:
        name: pdda-POSTGRES-USER
  environment:
    POSTGRES_USER: {{ Values.keyVaults.secrets.pdda-POSTGRES-USER}}