java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    RUN_DB_MIGRATION_ON_STARTUP: true
    POSTGRES_USER: "{{ .Values.postgresql.auth.username }}"
    APIM_ENABLED: true
    APIM_URI: https://sds-api-mgmt.staging.platform.hmcts.net/pip/data-management