SET client_encoding TO 'UTF8';

DROP SEQUENCE IF EXISTS xhb_courtel_list_seq CASCADE;

CREATE SEQUENCE xhb_courtel_list_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1;

DROP SEQUENCE IF EXISTS xhb_cath_document_link_seq CASCADE;

CREATE SEQUENCE xhb_cath_document_link_seq INCREMENT 1 MINVALUE 1 NO MAXVALUE START 1;
